version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11

    steps:
      - checkout

      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}

      - run: go get -v -u golang.org/x/lint/golint
      - run: golint ./...
      - run: make ci 
      - run: make test

      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
   